# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import nezha_pb2 as nezha__pb2

GRPC_GENERATED_VERSION = '1.81.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in nezha_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class NezhaServiceStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ReportSystemState = channel.unary_unary(
                '/proto.NezhaService/ReportSystemState',
                request_serializer=nezha__pb2.State.SerializeToString,
                response_deserializer=nezha__pb2.Receipt.FromString,
                _registered_method=True)
        self.ReportSystemInfo = channel.unary_unary(
                '/proto.NezhaService/ReportSystemInfo',
                request_serializer=nezha__pb2.Host.SerializeToString,
                response_deserializer=nezha__pb2.Receipt.FromString,
                _registered_method=True)
        self.ReportTask = channel.unary_unary(
                '/proto.NezhaService/ReportTask',
                request_serializer=nezha__pb2.TaskResult.SerializeToString,
                response_deserializer=nezha__pb2.Receipt.FromString,
                _registered_method=True)
        self.RequestTask = channel.unary_stream(
                '/proto.NezhaService/RequestTask',
                request_serializer=nezha__pb2.Host.SerializeToString,
                response_deserializer=nezha__pb2.Task.FromString,
                _registered_method=True)


class NezhaServiceServicer:
    """Missing associated documentation comment in .proto file."""

    def ReportSystemState(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReportSystemInfo(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReportTask(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RequestTask(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_NezhaServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ReportSystemState': grpc.unary_unary_rpc_method_handler(
                    servicer.ReportSystemState,
                    request_deserializer=nezha__pb2.State.FromString,
                    response_serializer=nezha__pb2.Receipt.SerializeToString,
            ),
            'ReportSystemInfo': grpc.unary_unary_rpc_method_handler(
                    servicer.ReportSystemInfo,
                    request_deserializer=nezha__pb2.Host.FromString,
                    response_serializer=nezha__pb2.Receipt.SerializeToString,
            ),
            'ReportTask': grpc.unary_unary_rpc_method_handler(
                    servicer.ReportTask,
                    request_deserializer=nezha__pb2.TaskResult.FromString,
                    response_serializer=nezha__pb2.Receipt.SerializeToString,
            ),
            'RequestTask': grpc.unary_stream_rpc_method_handler(
                    servicer.RequestTask,
                    request_deserializer=nezha__pb2.Host.FromString,
                    response_serializer=nezha__pb2.Task.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'proto.NezhaService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('proto.NezhaService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class NezhaService:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ReportSystemState(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/proto.NezhaService/ReportSystemState',
            nezha__pb2.State.SerializeToString,
            nezha__pb2.Receipt.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReportSystemInfo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/proto.NezhaService/ReportSystemInfo',
            nezha__pb2.Host.SerializeToString,
            nezha__pb2.Receipt.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReportTask(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/proto.NezhaService/ReportTask',
            nezha__pb2.TaskResult.SerializeToString,
            nezha__pb2.Receipt.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RequestTask(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/proto.NezhaService/RequestTask',
            nezha__pb2.Host.SerializeToString,
            nezha__pb2.Task.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
